import type { NextPage } from "next";
import Head from "next/head";
import ThemeSwitch from "../components/ThemeSwitch";
import Shell from "../components/Shell";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>QR - Find Things</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<h1>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<p>
					installed Extensions:{" "}
					<span className="text-draculaGreen">Tailwind</span>,{" "}
					<span className="text-draculaPurple">NextUI</span>
				</p>
			</Shell>
		</>
	);
};

export default Home;