import type { NextPage } from "next";
import Head from "next/head";
import ThemeSwitch from "../components/ThemeSwitch";
import Shell from "../components/Shell";
import SearchThing from "../components/SearchThing";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>QR - Find Things</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Shell>
				<main className="w-full flex flex-col items-center justify-center">
					<h1>
						Search for a thing
					</h1>
					<SearchThing />
				</main>
			</Shell>
		</>
	);
};

export default Home;
